services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`app-example-backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-public"

  traefik:
    image: "traefik:v2.11"
    depends_on:
      - backend
    ports:
      - "80:80"
      - "8080:8080"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik-public

networks:
  traefik-public:
